import { Image } from 'expo-image';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Pill, Screen, TopBar, palette } from '@/components/arc-ui';
import { cars } from '@/constants/mock-data';

export default function BookingConfirmationScreen() {
  const router = useRouter();
  const { carId, total } = useLocalSearchParams<{ carId?: string; total?: string }>();
  const car = cars.find((item) => item.id === carId) ?? cars[0];
  return <Screen><TopBar title="Booking submitted" /><ScrollView contentContainerStyle={styles.scroll}><View style={styles.success}><Text style={styles.check}>✓</Text><Text style={styles.successTitle}>Booking submitted</Text><Text style={styles.successText}>Your reservation is Pending Verification. Proof uploads never confirm a booking automatically.</Text></View><View style={styles.card}><View style={styles.bookingHead}><Text style={styles.bookingId}>BOOKING ID</Text><Text style={styles.id}>ARC-260925-14</Text></View><View style={styles.carRow}><Image source={{ uri: car.image }} style={styles.image} contentFit="cover" /><View><Text style={styles.carName}>{car.name}</Text><Text style={styles.carMeta}>{car.category}  •  {car.seats} seats</Text></View></View><Pill>Pending Verification</Pill><Detail label="Pickup" value="Sep 28, 2026 • 09:00 AM" /><Detail label="Return (fixed)" value="Oct 01, 2026 • 09:00 AM" /><Detail label="Pickup location" value="Davao City" /><Detail label="Travel destination" value="Provided in booking" /><Detail label="Estimated total" value={`₱${Number(total ?? car.price * 3).toLocaleString()}`} strong /></View><View style={styles.notice}><Text style={styles.noticeTitle}>Payment remains pending</Text><Text style={styles.noticeText}>ARC Car Rental must verify payment, the ₱1,000 down payment, and required documents before the booking becomes confirmed.</Text></View><Pressable style={styles.primary} onPress={() => router.push('/bookings' as never)}><Text style={styles.primaryText}>Go to my bookings</Text></Pressable><Pressable style={styles.secondary} onPress={() => router.replace('/home' as never)}><Text style={styles.secondaryText}>Back to home</Text></Pressable></ScrollView></Screen>;
}
function Detail({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={styles.detail}><Text style={styles.label}>{label}</Text><Text style={[styles.value, strong && styles.strong]}>{value}</Text></View>; }
const styles = StyleSheet.create({ scroll: { padding: 20, paddingBottom: 40 }, success: { alignItems: 'center', paddingVertical: 26 }, check: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#DDF7ED', color: palette.green, textAlign: 'center', lineHeight: 58, fontSize: 28, fontWeight: '900' }, successTitle: { color: palette.navy, fontSize: 24, fontWeight: '900', marginTop: 14 }, successText: { color: palette.muted, fontSize: 13, textAlign: 'center', marginTop: 6 }, card: { backgroundColor: palette.white, borderRadius: 18, padding: 17, borderWidth: 1, borderColor: '#E8EDF4' }, bookingHead: { flexDirection: 'row', justifyContent: 'space-between' }, bookingId: { color: palette.muted, fontSize: 10, fontWeight: '800' }, id: { color: palette.blue, fontSize: 11, fontWeight: '900' }, carRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 17 }, image: { width: 90, height: 65, borderRadius: 10, marginRight: 12 }, carName: { color: palette.navy, fontSize: 17, fontWeight: '800' }, carMeta: { color: palette.muted, fontSize: 12, marginTop: 5 }, detail: { borderTopWidth: 1, borderTopColor: '#EEF1F5', paddingTop: 12, marginTop: 13 }, label: { color: palette.muted, fontSize: 11 }, value: { color: palette.navy, fontSize: 14, fontWeight: '700', marginTop: 4 }, strong: { color: palette.blue, fontSize: 18 }, notice: { backgroundColor: '#FFF7E8', borderRadius: 15, padding: 15, marginTop: 16 }, noticeTitle: { color: '#A96800', fontSize: 14, fontWeight: '900' }, noticeText: { color: '#8B6D39', fontSize: 12, lineHeight: 18, marginTop: 5 }, primary: { backgroundColor: palette.blue, borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 20 }, primaryText: { color: palette.white, fontWeight: '800' }, secondary: { alignItems: 'center', padding: 16 }, secondaryText: { color: palette.blue, fontWeight: '800' },
});
