import { Image } from 'expo-image';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { BottomNav, Pill, Screen, TopBar, palette, styles as ui } from '@/components/arc-ui';
import { bookings } from '@/constants/mock-data';

export default function BookingsScreen() {
  const router = useRouter();
  return <Screen><TopBar title="My bookings" /><ScrollView contentContainerStyle={ui.scroll}><Text style={styles.title}>Your reservations</Text><Text style={styles.subtitle}>Keep track of every ARC Ride journey.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Text style={[styles.filter, styles.filterActive]}>All</Text><Text style={styles.filter}>Upcoming</Text><Text style={styles.filter}>Completed</Text><Text style={styles.filter}>Cancelled</Text></ScrollView>{bookings.map((booking) => <Pressable key={booking.id} style={styles.card} onPress={() => router.push({ pathname: '/booking-details' as never, params: { id: booking.id } })}><Image source={{ uri: booking.car.image }} style={styles.image} contentFit="cover" /><View style={styles.body}><View style={styles.top}><Text style={styles.id}>{booking.id}</Text><Pill tone={booking.status === 'Confirmed' ? 'green' : 'gray'}>{booking.status}</Pill></View><Text style={styles.name}>{booking.car.name}</Text><Text style={styles.date}>{booking.pickup}</Text><Text style={styles.location}>⌖  {booking.location}</Text><View style={styles.bottom}><Text style={styles.total}>₱{booking.total.toLocaleString()} total</Text><Text style={styles.details}>Details  ›</Text></View></View></Pressable>)}</ScrollView><BottomNav active="bookings" /></Screen>;
}
const styles = StyleSheet.create({ title: { color: palette.navy, fontSize: 28, fontWeight: '900', marginTop: 12 }, subtitle: { color: palette.muted, fontSize: 14, marginTop: 6 }, filters: { gap: 8, paddingVertical: 19 }, filter: { color: palette.muted, backgroundColor: palette.white, borderRadius: 20, paddingHorizontal: 15, paddingVertical: 9, fontSize: 12, fontWeight: '700' }, filterActive: { color: palette.white, backgroundColor: palette.blue }, card: { backgroundColor: palette.white, borderRadius: 18, overflow: 'hidden', marginBottom: 16, borderWidth: 1, borderColor: '#E8EDF4' }, image: { width: '100%', height: 150 }, body: { padding: 15 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, id: { color: palette.muted, fontSize: 10, fontWeight: '800' }, name: { color: palette.navy, fontSize: 18, fontWeight: '900', marginTop: 11 }, date: { color: palette.muted, fontSize: 12, marginTop: 7 }, location: { color: palette.muted, fontSize: 12, marginTop: 6 }, bottom: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#EEF1F5' }, total: { color: palette.navy, fontWeight: '800', fontSize: 13 }, details: { color: palette.blue, fontWeight: '800', fontSize: 12 },
});
