import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { Screen, TopBar, palette } from '@/components/arc-ui';

export default function ContactScreen() {
  return <Screen><TopBar back title="Contact us" /><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.title}>We are here to help</Text><Text style={styles.subtitle}>Reach ARC Car Rental before, during, or after your trip.</Text><View style={styles.card}><Info label="CALL" value="+63 917 123 4567" /><Info label="EMAIL" value="support@arcride.ph" /><Info label="LOCATION" value="Davao City, Philippines" /><Info label="BUSINESS HOURS" value="Mon - Sun • 8:00 AM - 8:00 PM" /></View><Text style={styles.section}>Send a message</Text><TextInput style={styles.input} placeholder="Your email" placeholderTextColor={palette.muted} keyboardType="email-address" /><TextInput style={[styles.input, styles.message]} placeholder="How can we help?" placeholderTextColor={palette.muted} multiline /><Pressable style={styles.button}><Text style={styles.buttonText}>Send message</Text></Pressable></ScrollView></Screen>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ scroll: { padding: 20, paddingBottom: 35 }, title: { color: palette.navy, fontSize: 29, fontWeight: '900', marginTop: 14 }, subtitle: { color: palette.muted, fontSize: 14, marginTop: 6 }, card: { backgroundColor: palette.white, borderRadius: 17, padding: 17, marginTop: 22, borderWidth: 1, borderColor: '#E8EDF4' }, info: { paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: '#EEF1F5' }, label: { color: palette.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, value: { color: palette.navy, fontSize: 14, fontWeight: '800', marginTop: 5 }, section: { color: palette.navy, fontSize: 18, fontWeight: '900', marginTop: 25, marginBottom: 10 }, input: { backgroundColor: palette.white, borderRadius: 13, borderWidth: 1, borderColor: palette.line, padding: 15, color: palette.ink, marginTop: 10 }, message: { height: 120, textAlignVertical: 'top' }, button: { backgroundColor: palette.blue, borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 16 }, buttonText: { color: palette.white, fontWeight: '800' },
});
