import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { palette, Screen, TopBar } from '@/components/arc-ui';
import { cars, ExtensionType } from '@/constants/mock-data';

const options: { type: ExtensionType; duration: string; cost: number }[] = [
  { type: 'Hourly', duration: '2 hours', cost: cars[2].hourlyPrice * 2 },
  { type: 'Daily', duration: '1 day', cost: cars[2].price },
  { type: 'Monthly', duration: '1 month', cost: cars[2].monthlyPrice },
];

export default function ExtensionScreen() {
  const router = useRouter();
  const [selected, setSelected] = useState<ExtensionType>('Daily');
  const choice = options.find((item) => item.type === selected) ?? options[1];
  const deadlinePassed = new Date() >= new Date('2026-10-01T09:00:00');
  return <Screen><TopBar back title="Extend rental" /><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.title}>Request more time</Text><Text style={styles.subtitle}>Extensions stay pending until ARC Car Rental approves the request.</Text><View style={styles.deadline}><Text style={styles.deadlineTitle}>{deadlinePassed ? 'Extension unavailable' : 'Extension request deadline: Sep 30, 2026 at 09:00 AM'}</Text><Text style={styles.deadlineText}>{deadlinePassed ? 'The scheduled return deadline has passed. Return the vehicle first and create a new booking to rent again.' : 'You can request before the original return date and fixed return time.'}</Text></View><Text style={styles.section}>Extension type</Text><View style={styles.options}>{options.map((item) => <Pressable key={item.type} onPress={() => setSelected(item.type)} style={[styles.option, selected === item.type && styles.optionActive]}><Text style={[styles.optionTitle, selected === item.type && styles.optionActiveText]}>{item.type}</Text><Text style={[styles.optionCost, selected === item.type && styles.optionActiveText]}>₱{item.cost.toLocaleString()}</Text><Text style={[styles.optionDuration, selected === item.type && styles.optionActiveText]}>{item.duration}</Text></Pressable>)}</View><View style={styles.card}><Info label="CURRENT RETURN DATE" value="October 01, 2026" /><Info label="CURRENT RETURN TIME (FIXED)" value="09:00 AM" /><Info label="ADDITIONAL COST" value={`₱${choice.cost.toLocaleString()}`} /><Info label="NEW REQUESTED RETURN" value={selected === 'Hourly' ? 'October 01, 2026 • 11:00 AM' : selected === 'Daily' ? 'October 02, 2026 • 09:00 AM' : 'November 01, 2026 • 09:00 AM'} /></View><Text style={styles.note}>Vehicle availability must be checked for the requested extension. If another booking conflicts, ARC Car Rental may arrange an equivalent replacement vehicle at no extra charge.</Text><Pressable disabled={deadlinePassed} style={[styles.button, deadlinePassed && styles.disabled]} onPress={() => router.replace('/extension-pending' as never)}><Text style={styles.buttonText}>{deadlinePassed ? 'Return vehicle first' : 'Submit extension request'}</Text></Pressable></ScrollView></Screen>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ scroll: { padding: 20, paddingBottom: 40 }, title: { color: palette.navy, fontSize: 29, fontWeight: '900', marginTop: 14 }, subtitle: { color: palette.muted, fontSize: 14, lineHeight: 21, marginTop: 7 }, deadline: { backgroundColor: '#FFF7E8', borderRadius: 15, padding: 16, marginTop: 20 }, deadlineTitle: { color: '#A96800', fontSize: 13, fontWeight: '900' }, deadlineText: { color: '#8B6D39', fontSize: 12, lineHeight: 18, marginTop: 5 }, section: { color: palette.navy, fontSize: 18, fontWeight: '800', marginTop: 24, marginBottom: 10 }, options: { flexDirection: 'row', gap: 8 }, option: { flex: 1, backgroundColor: palette.white, borderWidth: 1, borderColor: palette.line, borderRadius: 13, padding: 12 }, optionActive: { backgroundColor: palette.blue, borderColor: palette.blue }, optionTitle: { color: palette.navy, fontSize: 13, fontWeight: '900' }, optionCost: { color: palette.blue, fontSize: 14, fontWeight: '900', marginTop: 12 }, optionDuration: { color: palette.muted, fontSize: 10, marginTop: 3 }, optionActiveText: { color: palette.white }, card: { backgroundColor: palette.white, borderRadius: 17, padding: 17, marginTop: 20, borderWidth: 1, borderColor: '#E8EDF4' }, info: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#EEF1F5' }, label: { color: palette.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, value: { color: palette.navy, fontSize: 16, fontWeight: '800', marginTop: 5 }, note: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 16 }, button: { backgroundColor: palette.blue, borderRadius: 14, paddingVertical: 17, alignItems: 'center', marginTop: 22 }, disabled: { backgroundColor: '#B8C4D4' }, buttonText: { color: palette.white, fontWeight: '800' },
});
