import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { BottomNav, Screen, TopBar, palette, styles as ui } from '@/components/arc-ui';
import { notifications } from '@/constants/mock-data';

export default function NotificationsScreen() {
  return <Screen><TopBar title="Notifications" /><ScrollView contentContainerStyle={ui.scroll}><View style={styles.headingRow}><View><Text style={styles.title}>Your updates</Text><Text style={styles.subtitle}>Stay up to date with your rentals.</Text></View><Text style={styles.mark}>Mark all read</Text></View>{notifications.map((notification) => <View key={notification.id} style={[styles.card, notification.unread && styles.unread]}><View style={[styles.dot, !notification.unread && styles.dotRead]} /><View style={styles.body}><View style={styles.row}><Text style={styles.notificationTitle}>{notification.title}</Text><Text style={styles.time}>{notification.time}</Text></View><Text style={styles.notificationBody}>{notification.body}</Text></View></View>)}</ScrollView><BottomNav active="alerts" /></Screen>;
}
const styles = StyleSheet.create({ headingRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 12 }, title: { color: palette.navy, fontSize: 28, fontWeight: '900' }, subtitle: { color: palette.muted, fontSize: 14, marginTop: 6 }, mark: { color: palette.blue, fontSize: 11, fontWeight: '800', marginBottom: 3 }, card: { backgroundColor: palette.white, borderRadius: 16, padding: 16, flexDirection: 'row', marginTop: 14, borderWidth: 1, borderColor: '#E8EDF4' }, unread: { backgroundColor: '#F0F6FF', borderColor: '#D8E8FF' }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.blue, marginTop: 4, marginRight: 11 }, dotRead: { backgroundColor: '#C4CFDD' }, body: { flex: 1 }, row: { flexDirection: 'row', justifyContent: 'space-between' }, notificationTitle: { color: palette.navy, fontSize: 14, fontWeight: '900' }, time: { color: palette.muted, fontSize: 10 }, notificationBody: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 6 },
});
