import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';

import { BottomNav, Screen, TopBar, palette, styles as ui } from '@/components/arc-ui';

export default function ProfileScreen() {
  const router = useRouter();
  return <Screen><TopBar title="Profile" /><ScrollView contentContainerStyle={ui.scroll}><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>JD</Text></View><Text style={styles.name}>Juan Dela Cruz</Text><Text style={styles.email}>juan.delacruz@email.com</Text><Pressable style={styles.edit}><Text style={styles.editText}>Edit profile</Text></Pressable></View><View style={styles.trust}><View><Text style={styles.trustLabel}>ARC TRUST SCORE</Text><Text style={styles.menuDetail}>Managed by ARC Car Rental</Text></View><Text style={styles.trustValue}>92%</Text></View><Text style={styles.section}>Account</Text><View style={styles.menu}><MenuRow label="Personal information" detail="Name, phone, address" /><MenuRow label="Payment preferences" detail="Pay in person" /><MenuRow label="Booking history" detail="2 completed rentals" /></View><Text style={styles.section}>Preferences</Text><View style={styles.menu}><View style={styles.setting}><View><Text style={styles.menuLabel}>Notifications</Text><Text style={styles.menuDetail}>Booking and rental updates</Text></View><Switch value trackColor={{ false: '#D8E0EB', true: '#9EC2FF' }} thumbColor={palette.blue} /></View><MenuRow label="Help center" detail="We are here 24/7" /><MenuRow label="About ARC Ride" detail="Version 1.0.0" /></View><View style={styles.footer}><Text style={styles.footerTitle}>ARC CAR RENTAL</Text><View style={styles.footerLinks}><Text onPress={() => router.push('/about' as never)} style={styles.footerLink}>About Us</Text><Text onPress={() => router.push('/contact' as never)} style={styles.footerLink}>Contact</Text><Text onPress={() => router.push('/faq' as never)} style={styles.footerLink}>FAQ</Text></View></View><Pressable style={styles.logout} onPress={() => router.replace('/' as never)}><Text style={styles.logoutText}>Log out</Text></Pressable></ScrollView><BottomNav active="profile" /></Screen>;
}
function MenuRow({ label, detail }: { label: string; detail: string }) { return <Pressable style={styles.setting}><View><Text style={styles.menuLabel}>{label}</Text><Text style={styles.menuDetail}>{detail}</Text></View><Text style={styles.chevron}>›</Text></Pressable>; }
const styles = StyleSheet.create({ profile: { alignItems: 'center', paddingVertical: 19 }, avatar: { width: 76, height: 76, borderRadius: 38, backgroundColor: palette.blueSoft, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: palette.blue, fontSize: 24, fontWeight: '900' }, name: { color: palette.navy, fontSize: 21, fontWeight: '900', marginTop: 12 }, email: { color: palette.muted, fontSize: 13, marginTop: 4 }, edit: { borderWidth: 1, borderColor: '#BFD5F7', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginTop: 13 }, editText: { color: palette.blue, fontSize: 12, fontWeight: '800' }, trust: { backgroundColor: palette.navy, borderRadius: 16, padding: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, trustLabel: { color: '#93B9F5', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, trustValue: { color: palette.white, fontSize: 26, fontWeight: '900' }, section: { color: palette.navy, fontSize: 17, fontWeight: '800', marginTop: 18, marginBottom: 9 }, menu: { backgroundColor: palette.white, borderRadius: 16, paddingHorizontal: 16, borderWidth: 1, borderColor: '#E8EDF4' }, setting: { minHeight: 63, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#EEF1F5' }, menuLabel: { color: palette.navy, fontSize: 14, fontWeight: '800' }, menuDetail: { color: palette.muted, fontSize: 11, marginTop: 5 }, chevron: { color: palette.blue, fontSize: 23 }, footer: { alignItems: 'center', paddingVertical: 24 }, footerTitle: { color: palette.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, footerLinks: { flexDirection: 'row', gap: 18, marginTop: 10 }, footerLink: { color: palette.blue, fontSize: 12, fontWeight: '800' }, logout: { alignItems: 'center', padding: 18 }, logoutText: { color: '#D65B65', fontSize: 14, fontWeight: '800' },
});
