import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Screen, TopBar, palette } from '@/components/arc-ui';

export default function ReturnVehicleScreen() {
  const router = useRouter();
  const delayedHours = 2;
  const lateFee = delayedHours * 500;
  return <Screen><TopBar back title="Return vehicle" /><ScrollView contentContainerStyle={styles.scroll}><View style={styles.alert}><Text style={styles.alertIcon}>!</Text><Text style={styles.alertTitle}>Return Vehicle Mode</Text><Text style={styles.alertText}>Your return deadline has been reached. Please return the vehicle to ARC Car Rental as soon as possible.</Text></View><Text style={styles.section}>Return instructions</Text><View style={styles.card}><Text style={styles.instruction}>1. Bring the vehicle to the ARC Car Rental shop.</Text><Text style={styles.instruction}>2. Keep your keys and documents ready.</Text><Text style={styles.instruction}>3. A staff member will inspect and verify the return.</Text></View><Text style={styles.section}>Late-return estimate</Text><View style={styles.feeCard}><Row label="Scheduled return" value="10:00 AM" /><Row label="Reported return" value="12:00 PM" /><Row label="Delayed hours" value={`${delayedHours} hours`} /><Row label="Predefined late-return fee" value={`₱${lateFee.toLocaleString()}`} strong /></View><Text style={styles.note}>The final late-return fee is recorded after the vehicle is returned and verified. An expired rental cannot be extended; create a new booking after return.</Text><Pressable style={styles.button} onPress={() => router.replace('/bookings' as never)}><Text style={styles.buttonText}>I will return the vehicle</Text></Pressable></ScrollView></Screen>;
}
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={[styles.rowValue, strong && styles.strong]}>{value}</Text></View>; }
const styles = StyleSheet.create({ scroll: { padding: 20, paddingBottom: 40 }, alert: { backgroundColor: '#FFF7E8', borderRadius: 17, padding: 18, alignItems: 'center', marginTop: 15 }, alertIcon: { color: palette.white, backgroundColor: '#C9811A', width: 34, height: 34, borderRadius: 17, lineHeight: 34, textAlign: 'center', fontSize: 20, fontWeight: '900' }, alertTitle: { color: '#A96800', fontSize: 20, fontWeight: '900', marginTop: 11 }, alertText: { color: '#8B6D39', fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 5 }, section: { color: palette.navy, fontSize: 18, fontWeight: '800', marginTop: 24, marginBottom: 10 }, card: { backgroundColor: palette.white, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#E8EDF4' }, instruction: { color: palette.ink, fontSize: 13, lineHeight: 21, marginBottom: 9 }, feeCard: { backgroundColor: palette.navy, borderRadius: 16, padding: 17 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#30425E' }, rowLabel: { color: '#A9B7CA', fontSize: 12 }, rowValue: { color: palette.white, fontSize: 13, fontWeight: '700' }, strong: { color: '#8FBCFF', fontSize: 16 }, note: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 16 }, button: { backgroundColor: palette.blue, borderRadius: 14, paddingVertical: 17, alignItems: 'center', marginTop: 22 }, buttonText: { color: palette.white, fontWeight: '800' },
});
